spring.application.name=Console Game

# Cấu hình MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/game_console_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=A1234b1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Cấu hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Cầu hình google login
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

# Cấu hình gửi mail (Thay bằng email và Mật khẩu ứng dụng của bạn)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vtrong808@gmail.com
# Lưu ý: Đây là MẬT KHẨU ỨNG DỤNG (App Password) gồm 16 chữ số, KHÔNG phải mật khẩu đăng nhập Gmail
spring.mail.password=ofcz azdm njmb yhpm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true